{"b222bd8481e1767451379d634e26e4a9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"947e2fb67317e877","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/947e2fb67317e877","status":"passed","time":{"start":1677428794761,"stop":1677428794794,"duration":33}},{"uid":"926027c6941b40d6","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/926027c6941b40d6","status":"passed","time":{"start":1677424533037,"stop":1677424533063,"duration":26}},{"uid":"8a72a0c601245556","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8a72a0c601245556","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694403,"stop":1677422694403,"duration":0}}]},"be922e884fc0b322078bbd91d644a646":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"82de73b268598bc6","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/82de73b268598bc6","status":"passed","time":{"start":1677428792046,"stop":1677428792082,"duration":36}},{"uid":"ca2f1c41de0f2b68","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/ca2f1c41de0f2b68","status":"passed","time":{"start":1677424530843,"stop":1677424530867,"duration":24}},{"uid":"34ece8b0c747e6b9","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/34ece8b0c747e6b9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692989,"stop":1677422692989,"duration":0}}]},"5dea5b55e991fa0d651d962c092e5bfe":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"4f50c7cf1a4e1d68","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/4f50c7cf1a4e1d68","status":"passed","time":{"start":1677428791866,"stop":1677428791900,"duration":34}},{"uid":"d0d5515287fecea7","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/d0d5515287fecea7","status":"passed","time":{"start":1677424530710,"stop":1677424530735,"duration":25}},{"uid":"caae5559ea89ab53","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/caae5559ea89ab53","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692220,"stop":1677422692220,"duration":0}}]},"500b88c9e2c30d874c1710f6f6873043":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"47bd99a4da8ef33f","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/47bd99a4da8ef33f","status":"passed","time":{"start":1677428794857,"stop":1677428794891,"duration":34}},{"uid":"935d0b2aece1b520","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/935d0b2aece1b520","status":"passed","time":{"start":1677424533108,"stop":1677424533135,"duration":27}},{"uid":"cfd32284bd398b79","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/cfd32284bd398b79","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694864,"stop":1677422694864,"duration":0}}]},"69b2cce925f59635003662b7b0f2ff21":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"e112f6f6da1806c1","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/e112f6f6da1806c1","status":"passed","time":{"start":1677428792011,"stop":1677428792043,"duration":32}},{"uid":"8e0f7b9e0f076595","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/8e0f7b9e0f076595","status":"passed","time":{"start":1677424530815,"stop":1677424530841,"duration":26}},{"uid":"2d4af8a44d7dca04","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/2d4af8a44d7dca04","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692844,"stop":1677422692844,"duration":0}}]},"d8756eef83cee8a5f4dc8be4432511a3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"fa19a4e7f926d589","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/fa19a4e7f926d589","status":"passed","time":{"start":1677428782877,"stop":1677428782914,"duration":37}},{"uid":"b6a9a4a905867af3","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/b6a9a4a905867af3","status":"passed","time":{"start":1677424521946,"stop":1677424521971,"duration":25}},{"uid":"9dbbd391664b7296","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/9dbbd391664b7296","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690997,"stop":1677422690997,"duration":0}}]},"21a18d122fcae940f88903e0b0d8d7c7":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":7,"unknown":0,"total":7},"items":[{"uid":"f76eaa1e11230dd0","reportUrl":"https://uraniumcore238.github.io/discord/41//#testresult/f76eaa1e11230dd0","status":"passed","time":{"start":1677430293837,"stop":1677430293837,"duration":0}},{"uid":"c034a1098f3b4dd3","reportUrl":"https://uraniumcore238.github.io/discord/40//#testresult/c034a1098f3b4dd3","status":"passed","time":{"start":1677429631619,"stop":1677429631619,"duration":0}},{"uid":"e89def678b437fdc","reportUrl":"https://uraniumcore238.github.io/discord/39//#testresult/e89def678b437fdc","status":"passed","time":{"start":1677429241980,"stop":1677429241980,"duration":0}},{"uid":"c262dce63bd05e0c","reportUrl":"https://uraniumcore238.github.io/discord/38//#testresult/c262dce63bd05e0c","status":"passed","time":{"start":1677429066004,"stop":1677429066004,"duration":0}},{"uid":"ef3b5efdaf58f8e8","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/ef3b5efdaf58f8e8","status":"passed","time":{"start":1677428773843,"stop":1677428773843,"duration":0}},{"uid":"7e16a799312061d4","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/7e16a799312061d4","status":"passed","time":{"start":1677424519327,"stop":1677424519327,"duration":0}},{"uid":"f55123e407cd5ab0","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/f55123e407cd5ab0","status":"passed","time":{"start":1677422689890,"stop":1677422689890,"duration":0}}]},"11bf864f01a5895b5f5d4e0b8d2e9d88":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"b3c5e5e67ad529","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/b3c5e5e67ad529","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa679fce5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428797139,"stop":1677428797139,"duration":0}},{"uid":"fcf6d5aae40c970e","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/fcf6d5aae40c970e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f5ee950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534709,"stop":1677424534709,"duration":0}},{"uid":"e9d7f57d92c73012","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/e9d7f57d92c73012","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd5bee50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422696624,"stop":1677422696624,"duration":0}}]},"d8bc09f397575c83c8084a3920ba3d77":{"statistic":{"failed":2,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"908b3f84cc890ef8","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/908b3f84cc890ef8","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', \"[class*='footer']\")).element(('css selector', \"[href='/safety']\")).has exact text Safety\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href='/safety']\"}\n  (Session info: chrome=110.0.5481.100)\nStacktrace:\n#0 0x556e80322d93 <unknown>\n#1 0x556e800f12d7 <unknown>\n#2 0x556e8012dcaa <unknown>\n#3 0x556e8012ddb1 <unknown>\n#4 0x556e80122986 <unknown>\n#5 0x556e8015161d <unknown>\n#6 0x556e80122873 <unknown>\n#7 0x556e8015181e <unknown>\n#8 0x556e80169619 <unknown>\n#9 0x556e80151353 <unknown>\n#10 0x556e80120e40 <unknown>\n#11 0x556e80122038 <unknown>\n#12 0x556e803768be <unknown>\n#13 0x556e8037a8f0 <unknown>\n#14 0x556e8035af90 <unknown>\n#15 0x556e8037bb7d <unknown>\n#16 0x556e8034c578 <unknown>\n#17 0x556e803a0348 <unknown>\n#18 0x556e803a04d6 <unknown>\n#19 0x556e803ba341 <unknown>\n#20 0x7f286b630b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1677428773446/1677428773447.png\nPageSource: file:///home/runner/.selene/screenshots/1677428773446/1677428773447.html","time":{"start":1677428782954,"stop":1677428787199,"duration":4245}},{"uid":"91bff78483b799c0","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/91bff78483b799c0","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', \"[class*='footer']\")).element(('css selector', \"[href='/safety']\")).has exact text Safety\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href='/safety']\"}\n  (Session info: chrome=110.0.5481.100)\nStacktrace:\n#0 0x557fe913cd93 <unknown>\n#1 0x557fe8f0b2d7 <unknown>\n#2 0x557fe8f47caa <unknown>\n#3 0x557fe8f47db1 <unknown>\n#4 0x557fe8f3c986 <unknown>\n#5 0x557fe8f6b61d <unknown>\n#6 0x557fe8f3c873 <unknown>\n#7 0x557fe8f6b81e <unknown>\n#8 0x557fe8f83619 <unknown>\n#9 0x557fe8f6b353 <unknown>\n#10 0x557fe8f3ae40 <unknown>\n#11 0x557fe8f3c038 <unknown>\n#12 0x557fe91908be <unknown>\n#13 0x557fe91948f0 <unknown>\n#14 0x557fe9174f90 <unknown>\n#15 0x557fe9195b7d <unknown>\n#16 0x557fe9166578 <unknown>\n#17 0x557fe91ba348 <unknown>\n#18 0x557fe91ba4d6 <unknown>\n#19 0x557fe91d4341 <unknown>\n#20 0x7f7dc8982b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1677424519070/1677424519071.png\nPageSource: file:///home/runner/.selene/screenshots/1677424519070/1677424519071.html","time":{"start":1677424522000,"stop":1677424526208,"duration":4208}},{"uid":"fa036bf91a08645c","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/fa036bf91a08645c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691312,"stop":1677422691312,"duration":0}}]},"491976313902a9d9a530daa5df2a6c71":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"81ce603e7d224b16","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/81ce603e7d224b16","status":"passed","time":{"start":1677428787363,"stop":1677428787397,"duration":34}},{"uid":"b76f63003fb58cdd","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/b76f63003fb58cdd","status":"passed","time":{"start":1677424526322,"stop":1677424526349,"duration":27}},{"uid":"9b22d9144c21c05e","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/9b22d9144c21c05e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691456,"stop":1677422691456,"duration":0}}]},"595a8145431fa6b432b01286142b3ff0":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"b8f1c07bd7a5b264","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/b8f1c07bd7a5b264","status":"passed","time":{"start":1677428792120,"stop":1677428792152,"duration":32}},{"uid":"316d2796c351d84d","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/316d2796c351d84d","status":"passed","time":{"start":1677424530896,"stop":1677424530920,"duration":24}},{"uid":"5f65adce4277dfbe","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/5f65adce4277dfbe","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693301,"stop":1677422693301,"duration":0}}]},"d55ee81a3514f5c2febb5efd4a205826":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"783c4772cadb0f8","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/783c4772cadb0f8","status":"passed","time":{"start":1677428794827,"stop":1677428794854,"duration":27}},{"uid":"7bb6326612060a3c","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/7bb6326612060a3c","status":"passed","time":{"start":1677424533087,"stop":1677424533107,"duration":20}},{"uid":"e97e635d084312a3","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/e97e635d084312a3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694718,"stop":1677422694718,"duration":0}}]},"177bf47ad71d2c6a373169d721b4a8dc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"aa9c3cd224e6304f","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/aa9c3cd224e6304f","status":"passed","time":{"start":1677428794625,"stop":1677428794658,"duration":33}},{"uid":"6f99bb59cd7f58e8","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/6f99bb59cd7f58e8","status":"passed","time":{"start":1677424532776,"stop":1677424532962,"duration":186}},{"uid":"ab6d4ed7a0c6931","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/ab6d4ed7a0c6931","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693773,"stop":1677422693773,"duration":0}}]},"60d6b94a3ae57a737e98d0b797974837":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"b054e24f3533e48f","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/b054e24f3533e48f","status":"passed","time":{"start":1677428791902,"stop":1677428791935,"duration":33}},{"uid":"9cb02caf9e9d0598","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/9cb02caf9e9d0598","status":"passed","time":{"start":1677424530736,"stop":1677424530761,"duration":25}},{"uid":"a4153580ecd8f1aa","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/a4153580ecd8f1aa","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692383,"stop":1677422692383,"duration":0}}]},"af6a36f8aa85b2ef3c5fdd57f3801ce8":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8300e23c2db66d87","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/8300e23c2db66d87","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a139a20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428796266,"stop":1677428796266,"duration":0}},{"uid":"7ae0002c11f93148","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/7ae0002c11f93148","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f8f3b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534090,"stop":1677424534090,"duration":0}},{"uid":"8e0ad966688838bb","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8e0ad966688838bb","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd4dd890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695989,"stop":1677422695989,"duration":0}}]},"04e955e8efdddecde906f33889350980":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"6f5e139b5a3edcf8","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/6f5e139b5a3edcf8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a2be950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428796924,"stop":1677428796924,"duration":0}},{"uid":"f23d607699ac7969","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/f23d607699ac7969","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f4e4710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534561,"stop":1677424534561,"duration":0}},{"uid":"7a375da14f0596eb","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/7a375da14f0596eb","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bccfa5050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422696473,"stop":1677422696473,"duration":0}}]},"816984eb1c783f0075e85d653c62f416":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"88d9b6ce839ba1d9","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/88d9b6ce839ba1d9","status":"passed","time":{"start":1677428792155,"stop":1677428792186,"duration":31}},{"uid":"5569504478172fba","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/5569504478172fba","status":"passed","time":{"start":1677424530923,"stop":1677424530944,"duration":21}},{"uid":"1c1a3ad3e5150479","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/1c1a3ad3e5150479","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693475,"stop":1677422693475,"duration":0}}]},"0d1636b11e7dad598fdc84c6f66db4de":{"statistic":{"failed":2,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"1c0b3e279424d254","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/1c0b3e279424d254","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', \"[class*='footer']\")).element(('css selector', \"[href='/developers/docs']\")).has exact text Developers\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href='/developers/docs']\"}\n  (Session info: chrome=110.0.5481.100)\nStacktrace:\n#0 0x556e80322d93 <unknown>\n#1 0x556e800f12d7 <unknown>\n#2 0x556e8012dcaa <unknown>\n#3 0x556e8012ddb1 <unknown>\n#4 0x556e80122986 <unknown>\n#5 0x556e8015161d <unknown>\n#6 0x556e80122873 <unknown>\n#7 0x556e8015181e <unknown>\n#8 0x556e80169619 <unknown>\n#9 0x556e80151353 <unknown>\n#10 0x556e80120e40 <unknown>\n#11 0x556e80122038 <unknown>\n#12 0x556e803768be <unknown>\n#13 0x556e8037a8f0 <unknown>\n#14 0x556e8035af90 <unknown>\n#15 0x556e8037bb7d <unknown>\n#16 0x556e8034c578 <unknown>\n#17 0x556e803a0348 <unknown>\n#18 0x556e803a04d6 <unknown>\n#19 0x556e803ba341 <unknown>\n#20 0x7f286b630b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1677428773446/1677428773448.png\nPageSource: file:///home/runner/.selene/screenshots/1677428773446/1677428773448.html","time":{"start":1677428787435,"stop":1677428791676,"duration":4241}},{"uid":"21bf4516764f6235","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/21bf4516764f6235","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', \"[class*='footer']\")).element(('css selector', \"[href='/developers/docs']\")).has exact text Developers\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href='/developers/docs']\"}\n  (Session info: chrome=110.0.5481.100)\nStacktrace:\n#0 0x557fe913cd93 <unknown>\n#1 0x557fe8f0b2d7 <unknown>\n#2 0x557fe8f47caa <unknown>\n#3 0x557fe8f47db1 <unknown>\n#4 0x557fe8f3c986 <unknown>\n#5 0x557fe8f6b61d <unknown>\n#6 0x557fe8f3c873 <unknown>\n#7 0x557fe8f6b81e <unknown>\n#8 0x557fe8f83619 <unknown>\n#9 0x557fe8f6b353 <unknown>\n#10 0x557fe8f3ae40 <unknown>\n#11 0x557fe8f3c038 <unknown>\n#12 0x557fe91908be <unknown>\n#13 0x557fe91948f0 <unknown>\n#14 0x557fe9174f90 <unknown>\n#15 0x557fe9195b7d <unknown>\n#16 0x557fe9166578 <unknown>\n#17 0x557fe91ba348 <unknown>\n#18 0x557fe91ba4d6 <unknown>\n#19 0x557fe91d4341 <unknown>\n#20 0x7f7dc8982b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1677424519070/1677424519072.png\nPageSource: file:///home/runner/.selene/screenshots/1677424519070/1677424519072.html","time":{"start":1677424526377,"stop":1677424530570,"duration":4193}},{"uid":"251f61939f14f4ee","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/251f61939f14f4ee","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691762,"stop":1677422691762,"duration":0}}]},"6c6f11caf58a6be8840b57fae619464a":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"e2b77248394e220e","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/e2b77248394e220e","status":"passed","time":{"start":1677428782798,"stop":1677428782834,"duration":36}},{"uid":"eb07a32f3d5b7c2","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/eb07a32f3d5b7c2","status":"passed","time":{"start":1677424521892,"stop":1677424521917,"duration":25}},{"uid":"8da8913bcb8fdc96","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8da8913bcb8fdc96","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690691,"stop":1677422690691,"duration":0}}]},"6bb5a5fc132bd1e3a03b6cb58c193aa1":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"f293c8edaa9f1bdc","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/f293c8edaa9f1bdc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a540ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428794892,"stop":1677428794892,"duration":0}},{"uid":"634ed145b1167f99","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/634ed145b1167f99","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6faaf6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533136,"stop":1677424533136,"duration":0}},{"uid":"f89b1c3b63958cf3","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/f89b1c3b63958cf3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd068f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695010,"stop":1677422695010,"duration":0}}]},"00ce486fb67f877ddc901232a04d67c4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"8f58816644593e57","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/8f58816644593e57","status":"passed","time":{"start":1677428791793,"stop":1677428791827,"duration":34}},{"uid":"5780f42d70363c79","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/5780f42d70363c79","status":"passed","time":{"start":1677424530654,"stop":1677424530682,"duration":28}},{"uid":"affca5f9e5dbf5cf","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/affca5f9e5dbf5cf","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691929,"stop":1677422691929,"duration":0}}]},"2ad9dc5bfa57ce90a1e4a728ecd6b77f":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"931db33c643508c9","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/931db33c643508c9","status":"passed","time":{"start":1677428787399,"stop":1677428787432,"duration":33}},{"uid":"764f7fc1d80eea86","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/764f7fc1d80eea86","status":"passed","time":{"start":1677424526351,"stop":1677424526375,"duration":24}},{"uid":"8213d1291f18b41","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8213d1291f18b41","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691617,"stop":1677422691617,"duration":0}}]},"482ff5173726feec3562b5fdaa64878c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"89c35f7bf31aa7e","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/89c35f7bf31aa7e","status":"passed","time":{"start":1677428782917,"stop":1677428782951,"duration":34}},{"uid":"6c0444bbe06bc2bd","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/6c0444bbe06bc2bd","status":"passed","time":{"start":1677424521973,"stop":1677424521998,"duration":25}},{"uid":"1e7e43f31e120e29","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/1e7e43f31e120e29","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422691167,"stop":1677422691167,"duration":0}}]},"79a6432c68470a93d8e36a03d39540ca":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"2d8e8ea5eaec6fbe","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/2d8e8ea5eaec6fbe","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a5e2920>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428796689,"stop":1677428796689,"duration":0}},{"uid":"5a97a4c009e7f478","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/5a97a4c009e7f478","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f9f4f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534389,"stop":1677424534389,"duration":0}},{"uid":"128e5399f62bc531","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/128e5399f62bc531","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd3712d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422696319,"stop":1677422696319,"duration":0}}]},"2e29daab58a0adf2ceb1093b8a9ed3fe":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8119429154205ed8","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/8119429154205ed8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a1661a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428796029,"stop":1677428796029,"duration":0}},{"uid":"cad41303386420ba","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/cad41303386420ba","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f589250>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533919,"stop":1677424533919,"duration":0}},{"uid":"3ae44f8190c0d3db","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/3ae44f8190c0d3db","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bccf5a890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695812,"stop":1677422695812,"duration":0}}]},"e930917e0c52a468075fd7086717a7c7":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"a99ff17ae28b9e23","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/a99ff17ae28b9e23","status":"passed","time":{"start":1677428791830,"stop":1677428791863,"duration":33}},{"uid":"85ec0d1fc8a23513","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/85ec0d1fc8a23513","status":"passed","time":{"start":1677424530683,"stop":1677424530708,"duration":25}},{"uid":"76d1b288509eae01","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/76d1b288509eae01","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692074,"stop":1677422692074,"duration":0}}]},"7f03436489ba7c3eaca27dc156ea6587":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"86f2cd41bd5631d6","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/86f2cd41bd5631d6","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a45e530>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428796478,"stop":1677428796478,"duration":0}},{"uid":"704b17d17241a145","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/704b17d17241a145","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f5c9090>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534238,"stop":1677424534238,"duration":0}},{"uid":"584cd0760a61d97","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/584cd0760a61d97","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bccfc4290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422696140,"stop":1677422696140,"duration":0}}]},"753028a2508affe184d15f1467f591c9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"9d91119dbb18a863","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/9d91119dbb18a863","status":"passed","time":{"start":1677428794661,"stop":1677428794692,"duration":31}},{"uid":"22a4c5b7f82a0677","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/22a4c5b7f82a0677","status":"passed","time":{"start":1677424532965,"stop":1677424532989,"duration":24}},{"uid":"d595b26dd507b0c7","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/d595b26dd507b0c7","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693944,"stop":1677422693944,"duration":0}}]},"b783c60386e99cb82424504d88d70d17":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"4e48fa5abff90904","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/4e48fa5abff90904","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a245fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428795152,"stop":1677428795152,"duration":0}},{"uid":"2c4c7be33360707d","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/2c4c7be33360707d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f611b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533310,"stop":1677424533310,"duration":0}},{"uid":"225d4ab5036311df","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/225d4ab5036311df","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd65a7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695182,"stop":1677422695182,"duration":0}}]},"de27e30bf159b80cb1d613ef51bd77ca":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"937be9abba8fea89","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/937be9abba8fea89","status":"passed","time":{"start":1677428792084,"stop":1677428792117,"duration":33}},{"uid":"e1fe85cd6bdb0278","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/e1fe85cd6bdb0278","status":"passed","time":{"start":1677424530869,"stop":1677424530894,"duration":25}},{"uid":"43b50a3c8be541f2","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/43b50a3c8be541f2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693155,"stop":1677422693155,"duration":0}}]},"9d7280034391d6dcde21ff9b783051ec":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"a30c00046f3f31bb","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/a30c00046f3f31bb","status":"passed","time":{"start":1677428782096,"stop":1677428782184,"duration":88}},{"uid":"726f29ece95c4995","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/726f29ece95c4995","status":"passed","time":{"start":1677424521495,"stop":1677424521785,"duration":290}},{"uid":"7188f48f6c54d8dd","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/7188f48f6c54d8dd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690096,"stop":1677422690096,"duration":0}}]},"df877e2aea48755134f5e042e9ce6ba8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"61f2e77880f4d87a","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/61f2e77880f4d87a","status":"passed","time":{"start":1677428791938,"stop":1677428791969,"duration":31}},{"uid":"cfc75e1f6cb129e","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/cfc75e1f6cb129e","status":"passed","time":{"start":1677424530763,"stop":1677424530787,"duration":24}},{"uid":"cea5bf905de7d8b3","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/cea5bf905de7d8b3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692529,"stop":1677422692529,"duration":0}}]},"fe75c141123671b847c6180fcecf5abb":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"dc504d215539de55","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/dc504d215539de55","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a0da5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428795818,"stop":1677428795818,"duration":0}},{"uid":"3483dcea0094263c","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/3483dcea0094263c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f767b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533770,"stop":1677424533770,"duration":0}},{"uid":"168a73de5da2e391","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/168a73de5da2e391","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd2d7fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695661,"stop":1677422695661,"duration":0}}]},"13abdb216ca159f4ae55817b65263ef2":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"3bdefd00c5a2f6f4","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/3bdefd00c5a2f6f4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a3125c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428795365,"stop":1677428795365,"duration":0}},{"uid":"c9ae7950db00a4cd","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/c9ae7950db00a4cd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f98b310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533456,"stop":1677424533456,"duration":0}},{"uid":"1327ce63902d15d9","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/1327ce63902d15d9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bccfdf490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695334,"stop":1677422695334,"duration":0}}]},"68538b49d09f345c477432a374a3a804":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"3b2dd2d623a12505","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/3b2dd2d623a12505","status":"passed","time":{"start":1677428791972,"stop":1677428792009,"duration":37}},{"uid":"e9a093aa83e4b78f","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/e9a093aa83e4b78f","status":"passed","time":{"start":1677424530789,"stop":1677424530814,"duration":25}},{"uid":"1b2d138b84d05485","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/1b2d138b84d05485","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422692699,"stop":1677422692699,"duration":0}}]},"0f304db34f6536146077677251a5dd9d":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"e053969e00ef60e7","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/e053969e00ef60e7","status":"passed","time":{"start":1677428782761,"stop":1677428782795,"duration":34}},{"uid":"5c966040ba3ee7","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/5c966040ba3ee7","status":"passed","time":{"start":1677424521857,"stop":1677424521890,"duration":33}},{"uid":"765bdd5cadf7f857","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/765bdd5cadf7f857","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690547,"stop":1677422690547,"duration":0}}]},"bc85bd397ffbeda4f13b89f5d5d89c73":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"9980cbbc5c3eabb6","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/9980cbbc5c3eabb6","status":"passed","time":{"start":1677428782718,"stop":1677428782758,"duration":40}},{"uid":"c2ec5122f7760652","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/c2ec5122f7760652","status":"passed","time":{"start":1677424521828,"stop":1677424521855,"duration":27}},{"uid":"a98282b77c1acb5d","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/a98282b77c1acb5d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690403,"stop":1677422690403,"duration":0}}]},"0a15a95601a73d747e3f71baae4f744c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"2129800a1cb72d54","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/2129800a1cb72d54","status":"passed","time":{"start":1677428782190,"stop":1677428782712,"duration":522}},{"uid":"81417000e89e3eaa","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/81417000e89e3eaa","status":"passed","time":{"start":1677424521787,"stop":1677424521826,"duration":39}},{"uid":"4ff5e199841c51ab","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/4ff5e199841c51ab","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690240,"stop":1677422690240,"duration":0}}]},"8217a2fe0f4364823e0d2a5b43da08c5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"c8c42df2713e4a7d","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/c8c42df2713e4a7d","status":"passed","time":{"start":1677428782837,"stop":1677428782875,"duration":38}},{"uid":"439d916f26fa9bab","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/439d916f26fa9bab","status":"passed","time":{"start":1677424521919,"stop":1677424521945,"duration":26}},{"uid":"5b987f2c3d95b275","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/5b987f2c3d95b275","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422690853,"stop":1677422690853,"duration":0}}]},"81cf492b7bbe17b3f8325255e11f89dc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"98d6a26004ace655","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/98d6a26004ace655","status":"passed","time":{"start":1677428794728,"stop":1677428794758,"duration":30}},{"uid":"6f4d1a944f104454","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/6f4d1a944f104454","status":"passed","time":{"start":1677424533014,"stop":1677424533035,"duration":21}},{"uid":"807537f2037e508","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/807537f2037e508","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694236,"stop":1677422694236,"duration":0}}]},"da4444556c9f6f22b43300d3e8254f71":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":7,"unknown":0,"total":7},"items":[{"uid":"5aad1601c6b26829","reportUrl":"https://uraniumcore238.github.io/discord/41//#testresult/5aad1601c6b26829","status":"passed","time":{"start":1677430293633,"stop":1677430293835,"duration":202}},{"uid":"9513071c5e00297b","reportUrl":"https://uraniumcore238.github.io/discord/40//#testresult/9513071c5e00297b","status":"passed","time":{"start":1677429631377,"stop":1677429631616,"duration":239}},{"uid":"2e5c4fed1bb1b1c1","reportUrl":"https://uraniumcore238.github.io/discord/39//#testresult/2e5c4fed1bb1b1c1","status":"passed","time":{"start":1677429241843,"stop":1677429241978,"duration":135}},{"uid":"db9d8a6c971d4fc2","reportUrl":"https://uraniumcore238.github.io/discord/38//#testresult/db9d8a6c971d4fc2","status":"passed","time":{"start":1677429065859,"stop":1677429066002,"duration":143}},{"uid":"c67266ba78a5de41","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/c67266ba78a5de41","status":"passed","time":{"start":1677428773626,"stop":1677428773841,"duration":215}},{"uid":"9629d8a2cc7fa0a4","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/9629d8a2cc7fa0a4","status":"passed","time":{"start":1677424519162,"stop":1677424519325,"duration":163}},{"uid":"df4ef9e089d60c89","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/df4ef9e089d60c89","status":"passed","time":{"start":1677422689682,"stop":1677422689888,"duration":206}}]},"2fc1292b113a790861c80436fb13a641":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"473d59af700bff2f","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/473d59af700bff2f","status":"passed","time":{"start":1677428794694,"stop":1677428794726,"duration":32}},{"uid":"2008c1bf2351268c","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/2008c1bf2351268c","status":"passed","time":{"start":1677424532991,"stop":1677424533012,"duration":21}},{"uid":"60df0a28ce09c7ea","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/60df0a28ce09c7ea","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694091,"stop":1677422694091,"duration":0}}]},"49b0491d2450f499804ee62d6901a0c9":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"2ddccfa5df1a6911","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/2ddccfa5df1a6911","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a359990>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428795607,"stop":1677428795607,"duration":0}},{"uid":"7b20af5cf5a3faf9","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/7b20af5cf5a3faf9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f91fe50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424533603,"stop":1677424533603,"duration":0}},{"uid":"8d681b3bad83a086","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8d681b3bad83a086","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcce63dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422695510,"stop":1677422695510,"duration":0}}]},"eb45923660f570fcf55d4f30f1e716c2":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"8e31de68e4b4a1bd","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/8e31de68e4b4a1bd","status":"passed","time":{"start":1677428781724,"stop":1677428782093,"duration":369}},{"uid":"cbe76cf83a1b8e81","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/cbe76cf83a1b8e81","status":"passed","time":{"start":1677424521424,"stop":1677424521493,"duration":69}},{"uid":"8346ffc54fee8fe6","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/8346ffc54fee8fe6","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd6d89d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422689890,"stop":1677422689890,"duration":0}}]},"a2eb1f5ebd8044c7e0efa438f6b1258b":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8be48bf814ba0c79","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/8be48bf814ba0c79","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa67a461e40>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677428797385,"stop":1677428797385,"duration":0}},{"uid":"e8d6ef962de25f29","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/e8d6ef962de25f29","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e6f433890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677424534887,"stop":1677424534887,"duration":0}},{"uid":"2460c62fd4d0b4ab","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/2460c62fd4d0b4ab","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bccfa6490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422696801,"stop":1677422696801,"duration":0}}]},"bf96e753322758d87fc7d1224295c65a":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"ad9ac4edc12bc0b9","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/ad9ac4edc12bc0b9","status":"passed","time":{"start":1677428794797,"stop":1677428794824,"duration":27}},{"uid":"f99cecbb39404c94","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/f99cecbb39404c94","status":"passed","time":{"start":1677424533065,"stop":1677424533086,"duration":21}},{"uid":"7fbf3e75939619c0","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/7fbf3e75939619c0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422694549,"stop":1677422694549,"duration":0}}]},"6ed5f61a95ca4c2c6766ed9cf9dfed58":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"b4983e5f29e79952","reportUrl":"https://uraniumcore238.github.io/discord/36//#testresult/b4983e5f29e79952","status":"passed","time":{"start":1677428794142,"stop":1677428794621,"duration":479}},{"uid":"2196d10f09ba240c","reportUrl":"https://uraniumcore238.github.io/discord/35//#testresult/2196d10f09ba240c","status":"passed","time":{"start":1677424532481,"stop":1677424532770,"duration":289}},{"uid":"18f7d4b48fba117f","reportUrl":"https://uraniumcore238.github.io/discord/34//#testresult/18f7d4b48fba117f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bcd0aa850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1677422693621,"stop":1677422693621,"duration":0}}]}}